## NumPy = Numerical Python  

**a fundamental Python library for scientific computing and numerical operations.**

*It provides powerful tools for working with arrays, matrices, mathematical functions, and numerical data efficiently.*

In [ ]:
%pip install numpy

%pip install numpy
import numpy as np
print(f"NumPy version: {np.__version__}")
print(f"NumPy version: {np.__version__}")

: 

## Array 

a mathematical object that is defined to hold some numbers organized in rows and columns. The structure of the array should allow selecting (indexing) any of the inner items.


In [ ]:
import numpy as np

# 1D Array (Vector)
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)
print("Type:", type(arr_1d))
print("dtype:", arr_1d.dtype)

# 2D Array (Matrix)  
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("\n2D Array:")
print(arr_2d)

# 3D Array (Tensor) 
arr_3d = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("\n3D Array:")
print(arr_3d)
print("Shape:", arr_3d.shape)  # (2, 2, 2)


1D Array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>
dtype: int64

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)


In [ ]:
zeros = np.zeros((2,2))   # Create an array of all zeros
print(zeros)
print("\n")

ones = np.ones((5,2))    # Create an array of all ones
print(ones)
print("\n")

full = np.full(5,3)     # Create a constant array
print(full)
print("\n")

full = np.full((5,4), -9)  # Create a constant array
print(full)
print("\n")

eye = np.eye(5)         # Create a 5*5 identity matrix
print(eye)

[[0. 0.]
 [0. 0.]]


[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


[3 3 3 3 3]


[[-9 -9 -9 -9]
 [-9 -9 -9 -9]
 [-9 -9 -9 -9]
 [-9 -9 -9 -9]
 [-9 -9 -9 -9]]


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [69]:
random = np.random.random((2,2))  # Create an array filled with random values
print(random)

[[0.69984361 0.77951459]
 [0.02293309 0.57766286]]


In [ ]:
print("arange(10):", np.arange(10))
print("arange(1,10,2):", np.arange(1, 10, 2))

print("linspace(0, 1, 5):", np.linspace(0, 1, 5))
print("linspace(0, 100, 11):", np.linspace(0, 100, 11))

# arange determines number of steps
# linspace determines number of elements

arange(10): [0 1 2 3 4 5 6 7 8 9]
arange(1,10,2): [1 3 5 7 9]
linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]
linspace(0, 100, 11): [  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [23]:
import numpy as np

arr = np.array([[1.0, 2.0, 3.0],
                [4.0, 5.0, 6.0]])

print(f"arr.shape  = {arr.shape}")   
print(f"arr.ndim   = {arr.ndim}")    
print(f"arr.dtype  = {arr.dtype}")   
print(f"arr.size   = {arr.size}")    
print(f"arr.nbytes = {arr.nbytes}")   

print(f"arr.itemsize = {arr.itemsize}") 


arr.shape  = (2, 3)
arr.ndim   = 2
arr.dtype  = float64
arr.size   = 6
arr.nbytes = 48
arr.itemsize = 8


---
## أنواع البيانات (dtypes) 

| dtype | الحجم |
|-------|-------|
| int8 | 1 byte | 
| int32 | 4 bytes | 
| int64 | 8 bytes | 
| float32 | 4 bytes | 
| float64 | 8 bytes | 
| bool | 1 byte | 
| complex128 | 16 bytes | 


## Slicing and Indexing

In [24]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
#               0   1   2   3   4   5   6   7   8
#              -9  -8  -7  -6  -5  -4  -3  -2  -1

# Indexing
print("arr[0]  =", arr[0])    
print("arr[-1] =", arr[-1])   
print("arr[-3] =", arr[-3])   

# Slicing [start:stop:step]
print("\narr[2:6]    =", arr[2:6])     
print("arr[:4]     =", arr[:4])       
print("arr[5:]     =", arr[5:])        
print("arr[::2]    =", arr[::2])       
print("arr[::-1]   =", arr[::-1])       
print("arr[1:8:3]  =", arr[1:8:3])   


arr[0]  = 10
arr[-1] = 90
arr[-3] = 70

arr[2:6]    = [30 40 50 60]
arr[:4]     = [10 20 30 40]
arr[5:]     = [60 70 80 90]
arr[::2]    = [10 30 50 70 90]
arr[::-1]   = [90 80 70 60 50 40 30 20 10]
arr[1:8:3]  = [20 50 80]


In [ ]:
matrix = np.array([[1,  2,  3,  4],
                   [5,  6,  7,  8],
                   [9, 10, 11, 12]])

#Indexing
print(matrix[1, 2],"\n")

#Slicing
print(matrix[0],"\n")       
print(matrix[:, 0],"\n")      
print(matrix[:2],"\n")       
print(matrix[:2, :3])


7 

[1 2 3 4] 

[1 5 9] 

[[1 2 3 4]
 [5 6 7 8]] 

[[1 2 3]
 [5 6 7]]


In [71]:
# Indexing 
import numpy as np

tensor = np.arange(24).reshape(2, 3, 4)
print("Tensor (2, 3, 4):")
print(tensor)
print(f"\ntensor[0] =\n{tensor[0]}")                 
print(f"\ntensor[1,2,3] = {tensor[1,2,3]}")     
print(f"\ntensor[0,2,1] = {tensor[0,2,1]}")              
print(f"\ntensor[:, 0, :] =\n{tensor[:, 0, :]}") 


Tensor (2, 3, 4):
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

tensor[0] =
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

tensor[1,2,3] = 23

tensor[0,2,1] = 9

tensor[:, 0, :] =
[[ 0  1  2  3]
 [12 13 14 15]]


## Boolean Masking

In [ ]:
import numpy as np

scores = np.array([45, 82, 91, 67, 55, 88, 73, 95, 61, 79])

# Boolean Mask
mask = scores > 75
print("Mask:", mask)
print(scores[mask])

# filter with conditions
print(scores[(scores >= 60) & (scores <= 80)])
print(scores[(scores < 60) | (scores > 90)])


Mask: [False  True  True False False  True False  True False  True]
[82 91 88 95 79]
[67 73 61 79]
[45 91 55 95]


## Reshaping

In [33]:
import numpy as np

arr = np.arange(12)
print("Original:", arr)

# reshape
m_new = arr.reshape(3, 4)
print("\nreshape(3,4):\n", m_new)

m_reshaped = arr.reshape(2, 6)
print("\nreshape(2,6):\n", m_reshaped)

Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]

reshape(3,4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

reshape(2,6):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [ ]:
import numpy as np

matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])

# Copy
flat = matrix.flatten()
print("flatten():", flat)

# View so it is faster
rav = matrix.ravel()
print("ravel():", rav)

flatten(): [1 2 3 4 5 6 7 8 9]
ravel(): [1 2 3 4 5 6 7 8 9]


## Mathimatical Operations

**like summation, substraction, multiplication, division and other operations**

In [42]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print("arr + 10  =", arr + 10)
print("arr * 3   =", arr * 3)
print("arr / 2   =", arr / 2)
print("arr ** 2  =", arr ** 2)

print("\narr > 3 =", arr > 3)
print("arr == 3 =", arr == 3)


arr + 10  = [11 12 13 14 15]
arr * 3   = [ 3  6  9 12 15]
arr / 2   = [0.5 1.  1.5 2.  2.5]
arr ** 2  = [ 1  4  9 16 25]

arr > 3 = [False False False  True  True]
arr == 3 = [False False  True False False]


In [ ]:
x = np.array([[1,2],
              [3,4]])
y = np.array([[5,6],
              [7,8]])
print(x)
print(y,"\n")

# Elementwise sum

print(x + y)
print(np.add(x, y),"\n")


# Elementwise difference

print(x - y)
print(np.subtract(x, y),"\n")


# Elementwise product

print(x * y)
print(np.multiply(x, y),"\n")


# Elementwise division

print(x / y)
print(np.divide(x, y),"\n")


[[1 2]
 [3 4]]
[[5 6]
 [7 8]] 

[[ 6  8]
 [10 12]]
[[ 6  8]
 [10 12]] 

[[-4 -4]
 [-4 -4]]
[[-4 -4]
 [-4 -4]] 

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]] 

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]] 



In [41]:
# Elementwise square root

print(np.sqrt(x),"\n")

# Transpose of a Matrix

print(x.T,"\n")

# Dot Product

np.dot(x, y)

[[1.         1.41421356]
 [1.73205081 2.        ]] 

[[1 3]
 [2 4]] 



array([[19, 22],
       [43, 50]])

In [43]:
import numpy as np

arr = np.array([1, 4, 9, 16, 25, 36])

print("sqrt:", np.sqrt(arr))
print("square:", np.square(arr))
print("abs:", np.abs(np.array([-1, -2, 3, -4])))
print("log:", np.log(arr))        
print("log2:", np.log2(arr))
print("log10:", np.log10(arr))
print("exp:", np.exp(np.array([0, 1, 2])))  # e^x


sqrt: [1. 2. 3. 4. 5. 6.]
square: [   1   16   81  256  625 1296]
abs: [1 2 3 4]
log: [0.         1.38629436 2.19722458 2.77258872 3.21887582 3.58351894]
log2: [0.         2.         3.169925   4.         4.64385619 5.169925  ]
log10: [0.         0.60205999 0.95424251 1.20411998 1.39794001 1.5563025 ]
exp: [1.         2.71828183 7.3890561 ]


In [46]:
import numpy as np

angles = np.linspace(0, np.pi, 3)
print("angles (rad):", angles.round(3))
print("sin:", np.sin(angles).round(3))
print("cos:", np.cos(angles).round(3))

print("\nceil:", np.ceil(np.array([1.2, 2.7, 3.1])))
print("floor:", np.floor(np.array([1.9, 2.7, 3.9])))
print("round:", np.round(np.array([1.4567, 2.678, 3.333]), 2))

angles (rad): [0.    1.571 3.142]
sin: [0. 1. 0.]
cos: [ 1.  0. -1.]

ceil: [2. 3. 4.]
floor: [1. 2. 3.]
round: [1.46 2.68 3.33]


In [47]:
import numpy as np

arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3])

print(f"sum    = {np.sum(arr)}")
print(f"mean   = {np.mean(arr)}")
print(f"median = {np.median(arr)}")
print(f"std    = {np.std(arr):.3f}")     
print(f"var    = {np.var(arr):.3f}")     
print(f"min    = {np.min(arr)}")
print(f"max    = {np.max(arr)}")
print(f"argmin = {np.argmin(arr)}")      
print(f"argmax = {np.argmax(arr)}")       
print(f"cumsum = {np.cumsum(arr)}")    
print(f"cumprod= {np.cumprod(np.array([1,2,3,4,5]))}")  


sum    = 39
mean   = 3.9
median = 3.5
std    = 2.343
var    = 5.490
min    = 1
max    = 9
argmin = 1
argmax = 5
cumsum = [ 3  4  8  9 14 23 25 31 36 39]
cumprod= [  1   2   6  24 120]


In [48]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Matrix:")
print(matrix)

print("\nsum", np.sum(matrix))
print("sum axis=0:", np.sum(matrix, axis=0))  
print("sum axis=1:", np.sum(matrix, axis=1))   
print("mean axis=0:", np.mean(matrix, axis=0))
print("max axis=1:", np.max(matrix, axis=1))


Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

sum 45
sum axis=0: [12 15 18]
sum axis=1: [ 6 15 24]
mean axis=0: [4. 5. 6.]
max axis=1: [3 6 9]


In [49]:
# Percentiles
data = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print("25th percentile:", np.percentile(data, 25))
print("50th percentile:", np.percentile(data, 50))   
print("75th percentile:", np.percentile(data, 75))
print("IQR:", np.percentile(data, 75) - np.percentile(data, 25))   # used to detect outliers

25th percentile: 32.5
50th percentile: 55.0
75th percentile: 77.5
IQR: 45.0


## Linear Algebra

In [ ]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

# Matrix Multiplication
print("A @ B:")
print(A @ B)

# Transpose
print("\nA.T:")
print(A.T)

# Determinant
print("\ndet(A):", np.linalg.det(A))

# Inverse
print("\ninv(A):")
print(np.linalg.inv(A).round(3))

# Verification: A × inv(A) = I
print("\nA @ inv(A) = I?")
print((A @ np.linalg.inv(A)).round(10))


A @ B:
[[19 22]
 [43 50]]

A.T:
[[1 3]
 [2 4]]

det(A): -2.0000000000000004

inv(A):
[[-2.   1. ]
 [ 1.5 -0.5]]

A @ inv(A) = I?
[[1. 0.]
 [0. 1.]]


In [61]:
import numpy as np

# Eigenvalues و Eigenvectors
A = np.array([[4, 1],
              [2, 3]])

eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

# Norm
v = np.array([3, 4])
print("\nL2 Norm:", np.linalg.norm(v))   
print("L1 Norm:", np.linalg.norm(v, ord=1)) 

Eigenvalues: [5. 2.]
Eigenvectors:
 [[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]

L2 Norm: 5.0
L1 Norm: 7.0


In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

print("concatenate 1D:", np.concatenate([a, b, c]),"\n")

# 2D
A = np.array([[1,2],
              [3,4]])
B = np.array([[5,6],
              [7,8]])

print(np.concatenate([A, B], axis=0),"\n")

print(np.concatenate([A, B], axis=1))


concatenate 1D: [1 2 3 4 5 6 7 8 9] 

[[1 2]
 [3 4]
 [5 6]
 [7 8]] 

[[1 2 5 6]
 [3 4 7 8]]


In [55]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("vstack:")
print(np.vstack([a, b]))

print("\nhstack:")
print(np.hstack([a, b]))

vstack:
[[1 2 3]
 [4 5 6]]

hstack:
[1 2 3 4 5 6]


In [56]:
import numpy as np
import pandas as pd

df = pd.DataFrame({'A': [1,2,3,4,5], 'B': [10,20,30,40,50]})

arr = df.values       
print("df.values:", arr)
print("type:", type(arr))
print("dtype:", arr.dtype)


df.values: [[ 1 10]
 [ 2 20]
 [ 3 30]
 [ 4 40]
 [ 5 50]]
type: <class 'numpy.ndarray'>
dtype: int64


In [57]:
import numpy as np
import pandas as pd

np_arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

# np → DataFrame
df = pd.DataFrame(np_arr, columns=['X','Y','Z'])
print(df)

# DataFrame → np
back_to_np = df.values
print("\n",back_to_np)


   X  Y  Z
0  1  2  3
1  4  5  6
2  7  8  9

 [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
import numpy as np
import pandas as pd

arr = np.array([1.0, np.nan, 3.0, np.nan, 5.0])
s = pd.Series(arr)
print(s)
print("\nisnull:", s.isnull().values)
print("fillna(0):", s.fillna(0).values)

0    1.0
1    NaN
2    3.0
3    NaN
4    5.0
dtype: float64

isnull: [False  True False  True False]
fillna(0): [1. 0. 3. 0. 5.]
fillna(0): [ 1. nan  3. nan  5.]
