# 🔢 محاضرة NumPy الشاملة — من الصفر للاحتراف

---

## 📋 المحتويات

| # | الموضوع | الوصف |
|---|---------|-------|
| 1 | ما هو NumPy ولماذا نستخدمه؟ | Array vs List، السرعة، الذاكرة |
| 2 | تثبيت واستيراد | pip، الـ convention |
| 3 | إنشاء Arrays | zeros, ones, arange, linspace, random |
| 4 | الـ Attributes | shape, ndim, dtype, size |
| 5 | أنواع البيانات (dtypes) | int, float, bool, complex |
| 6 | Indexing و Slicing (1D) | الوصول للعناصر |
| 7 | Indexing و Slicing (2D و 3D) | الأبعاد المتعددة |
| 8 | Fancy Indexing | فلترة بـ arrays |
| 9 | Boolean Indexing | فلترة بالشروط |
| 10 | تعديل الشكل (Reshaping) | reshape, flatten, ravel, transpose |
| 11 | العمليات الحسابية الأساسية | +، -، *، / على Arrays |
| 12 | Universal Functions (ufuncs) | sqrt, exp, log, sin, cos |
| 13 | Aggregation Functions | sum, mean, std, min, max |
| 14 | Broadcasting | العمليات بين Arrays مختلفة الحجم |
| 15 | Linear Algebra | dot, matmul, det, inv, eigenvalues |
| 16 | Random Module | rand, randn, randint, seed, shuffle |
| 17 | Sorting و Searching | sort, argsort, where, argmin, argmax |
| 18 | دمج وتقسيم Arrays | concatenate, stack, split, vstack, hstack |
| 19 | التعامل مع القيم المفقودة | nan, isnan, nanmean |
| 20 | Array Copy vs View | الفرق المهم جداً |
| 21 | Vectorization بدل Loops | السرعة الحقيقية |
| 22 | NumPy و Pandas | الربط بين المكتبتين |
| 23 | مشروع تطبيقي | حسابات إحصائية وتحليل بيانات |

---
> 💡 **كل section = شرح نظري + أمثلة عملية + ملاحظات للـ ML**


---
## 1️⃣ ما هو NumPy ولماذا نستخدمه؟

**NumPy** = **Num**erical **Py**thon — مكتبة الحسابات العلمية الأساسية في Python.

### 🐌 المشكلة مع Lists العادية


In [3]:
import time

# ── قياس السرعة: List vs Array ──
size = 1_000_000

# Python List
py_list = list(range(size))
t0 = time.time()
result_list = [x * 2 for x in py_list]
t_list = time.time() - t0

# NumPy Array
import numpy as np
np_arr = np.arange(size)
t0 = time.time()
result_arr = np_arr * 2
t_arr = time.time() - t0

print(f"Python List:  {t_list*1000:.2f} ms")
print(f"NumPy Array:  {t_arr*1000:.2f} ms")
print(f"NumPy أسرع بـ: {t_list/t_arr:.0f}x تقريباً")


Python List:  158.56 ms
NumPy Array:  4.20 ms
NumPy أسرع بـ: 38x تقريباً


In [4]:
# ── قياس الذاكرة: List vs Array ──
import sys
import numpy as np

size = 1000
py_list = list(range(size))
np_arr  = np.arange(size, dtype=np.int64)

mem_list = sys.getsizeof(py_list) + sum(sys.getsizeof(i) for i in py_list)
mem_arr  = np_arr.nbytes

print(f"Python List:  {mem_list:,} bytes")
print(f"NumPy Array:  {mem_arr:,} bytes")
print(f"NumPy أوفر في الذاكرة بنسبة: {(1 - mem_arr/mem_list)*100:.0f}%")


Python List:  36,056 bytes
NumPy Array:  8,000 bytes
NumPy أوفر في الذاكرة بنسبة: 78%


### 🤔 ليه NumPy أسرع؟

| الفرق | Python List | NumPy Array |
|-------|------------|-------------|
| التخزين | كل عنصر object منفصل في الذاكرة | عناصر متجاورة في الذاكرة (contiguous) |
| النوع | mixed types (int, str, ...) | نوع واحد ثابت |
| العمليات | loop في Python (بطيء) | C وFortran في الخلفية (سريع) |
| البث | مش موجود | Broadcasting |

> 🧠 **للـ ML:** كل الـ models بتشتغل على Arrays — weights, gradients, predictions = كلها NumPy arrays في القلب.


---
## 2️⃣ تثبيت واستيراد

In [164]:
# تثبيت (في الـ Terminal)
!pip install numpy

# الاستيراد — الـ convention العالمي دايماً np
import numpy as np

print(f"NumPy version: {np.__version__}")
print(f"NumPy location: {np.__file__}")


NumPy version: 1.26.4
NumPy location: E:\Users\FreeComp\anaconda3\Lib\site-packages\numpy\__init__.py


---
## 3️⃣ إنشاء Arrays

### 📌 3.1 — من Lists

In [9]:
import numpy as np

# 1D Array (Vector)
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:", arr_1d)
print("Type:", type(arr_1d))
print("dtype:", arr_1d.dtype)

# 2D Array (Matrix)
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("\n2D Array:")
print(arr_2d)

# 3D Array (Tensor)
arr_3d = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("\n3D Array:")
print(arr_3d)
print("Shape:", arr_3d.shape)  # (2, 2, 2)


1D Array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>
dtype: int32

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

3D Array:
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
Shape: (2, 2, 2)


### 📌 3.2 — دوال الإنشاء الجاهزة

In [11]:
import numpy as np

# zeros و ones
print("zeros(5):", np.zeros(5))
print("ones(5):", np.ones(5))
print("zeros (2x3):\n", np.zeros((2, 3)))
print("ones (3x3):\n", np.ones((3, 3)))


zeros(5): [0. 0. 0. 0. 0.]
ones(5): [1. 1. 1. 1. 1.]
zeros (2x3):
 [[0. 0. 0.]
 [0. 0. 0.]]
ones (3x3):
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [12]:
# full — ملء بقيمة معينة
print("full(5, 7):", np.full(5, 7))
print("full (2x3, 99):\n", np.full((2, 3), 99))

# eye — مصفوفة الهوية (Identity Matrix)
print("\neye(4):\n", np.eye(4))


full(5, 7): [7 7 7 7 7]
full (2x3, 99):
 [[99 99 99]
 [99 99 99]]

eye(4):
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [13]:
# arange — مثل range لكن بيرجع Array
print("arange(10):", np.arange(10))
print("arange(1,10,2):", np.arange(1, 10, 2))      # كل خطوتين
print("arange(0,1,0.1):", np.arange(0, 1, 0.1))   # float steps


arange(10): [0 1 2 3 4 5 6 7 8 9]
arange(1,10,2): [1 3 5 7 9]
arange(0,1,0.1): [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]


In [168]:
# linspace — N نقطة متساوية البعد بين قيمتين
print("linspace(0, 1, 5):", np.linspace(0, 1, 5))
print("linspace(0, 100, 11):", np.linspace(0, 100, 11))

# الفرق بين arange و linspace:
# arange: تحدد الخطوة  → عدد العناصر مش مضمون
# linspace: تحدد عدد العناصر → الخطوة بتتحسب أوتوماتيك


linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]
linspace(0, 100, 11): [  0.  10.  20.  30.  40.  50.  60.  70.  80.  90. 100.]


In [145]:
np.arange(0, 100, 11)  

array([ 0, 11, 22, 33, 44, 55, 66, 77, 88, 99])

In [172]:
# empty — Array فاضية (بيانات عشوائية من الذاكرة — أسرع للـ init)
print("empty(3):", np.empty(3))   # قيم غير محددة

# diag — مصفوفة diagonal
print("\ndiag([1,2,3,4]):\n", np.diag([1, 2, 3, 4]))


empty(3): [0. 0. 0.]

diag([1,2,3,4]):
 [[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


---
## 4️⃣ الـ Attributes — خصائص Array

> 🔑 **أول ما تاخد أي Array، اتعرف عليها بالـ attributes دي.**


In [17]:
import numpy as np

arr = np.array([[1.0, 2.0, 3.0],
                [4.0, 5.0, 6.0]])

print(f"arr.shape  = {arr.shape}")    # (2, 3) — صفين، 3 أعمدة
print(f"arr.ndim   = {arr.ndim}")     # 2 — بُعدين
print(f"arr.dtype  = {arr.dtype}")    # float64
print(f"arr.size   = {arr.size}")     # 6 — عدد العناصر الكلي
print(f"arr.nbytes = {arr.nbytes}")   # 48 bytes (6 × 8)

# itemsize: حجم كل عنصر بالـ bytes
print(f"arr.itemsize = {arr.itemsize}")  # 8 bytes للـ float64


arr.shape  = (2, 3)
arr.ndim   = 2
arr.dtype  = float64
arr.size   = 6
arr.nbytes = 48
arr.itemsize = 8


In [18]:
# shape في الـ ML يعني إيه؟
import numpy as np

# Dataset
X = np.random.randn(100, 5)   # 100 sample, 5 features
y = np.random.randn(100)       # 100 target values
W = np.random.randn(5, 1)      # weights matrix

print(f"X.shape = {X.shape}  → (samples, features)")
print(f"y.shape = {y.shape}  → (samples,)")
print(f"W.shape = {W.shape}  → (features, outputs)")


X.shape = (100, 5)  → (samples, features)
y.shape = (100,)  → (samples,)
W.shape = (5, 1)  → (features, outputs)


---
## 5️⃣ أنواع البيانات (dtypes) 🔢

| dtype | الحجم | النطاق / الدقة | الاستخدام |
|-------|-------|----------------|-----------|
| int8 | 1 byte | -128 → 127 | صور (pixel values) |
| int32 | 4 bytes | -2B → 2B | IDs |
| int64 | 8 bytes | كبير جداً | default int |
| float32 | 4 bytes | ~7 خانة عشرية | ML models (أسرع على GPU) |
| float64 | 8 bytes | ~15 خانة عشرية | default float |
| bool | 1 byte | True/False | masks |
| complex128 | 16 bytes | أعداد مركبة | Signal processing |


In [20]:
import numpy as np

# تحديد الـ dtype عند الإنشاء
a_int8   = np.array([1, 2, 3], dtype=np.int8)
a_float32= np.array([1.0, 2.0, 3.0], dtype=np.float32)
a_bool   = np.array([True, False, True], dtype=bool)
a_complex= np.array([1+2j, 3+4j], dtype=complex)

print(f"int8:    {a_int8},   dtype={a_int8.dtype},   bytes={a_int8.nbytes}")
print(f"float32: {a_float32}, dtype={a_float32.dtype}, bytes={a_float32.nbytes}")
print(f"bool:    {a_bool},   dtype={a_bool.dtype},   bytes={a_bool.nbytes}")
print(f"complex: {a_complex},  dtype={a_complex.dtype}")


int8:    [1 2 3],   dtype=int8,   bytes=3
float32: [1. 2. 3.], dtype=float32, bytes=12
bool:    [ True False  True],   dtype=bool,   bytes=3
complex: [1.+2.j 3.+4.j],  dtype=complex128


In [21]:
# تحويل dtype — astype()
import numpy as np

arr = np.array([1, 2, 3, 4])
print("Original (int64):", arr.dtype)

arr_float = arr.astype(np.float32)
print("Converted (float32):", arr_float, arr_float.dtype)

arr_bool = arr.astype(bool)
print("As bool:", arr_bool)  # 0=False, غير ذلك=True

# ⚠️ overflow مع int8
arr_big = np.array([200, 300], dtype=np.int8)
print("Overflow مع int8:", arr_big)  # بيلف!


Original (int64): int32
Converted (float32): [1. 2. 3. 4.] float32
As bool: [ True  True  True  True]
Overflow مع int8: [-56  44]


C:\Users\FreeComp\AppData\Local\Temp\ipykernel_18516\1424488020.py:14: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 200 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  arr_big = np.array([200, 300], dtype=np.int8)
C:\Users\FreeComp\AppData\Local\Temp\ipykernel_18516\1424488020.py:14: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 300 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  arr_big = np.array([200, 300], dtype=np.int8)


---
## 6️⃣ Indexing و Slicing (1D) 🎯

> نفس فكرة Python lists — لكن بإمكانيات أكتر.


In [ ]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])


In [23]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90])
#               0   1   2   3   4   5   6   7   8
#              -9  -8  -7  -6  -5  -4  -3  -2  -1

# Indexing
print("arr[0]  =", arr[0])    # 10
print("arr[-1] =", arr[-1])   # 90 (من الآخر)
print("arr[-3] =", arr[-3])   # 70

# Slicing [start:stop:step]
print("\narr[2:6]    =", arr[2:6])     # 30,40,50,60
print("arr[:4]     =", arr[:4])         # 10,20,30,40
print("arr[5:]     =", arr[5:])         # 60,70,80,90
print("arr[::2]    =", arr[::2])        # كل خطوتين
print("arr[::-1]   =", arr[::-1])       # عكس الـ Array
print("arr[1:8:3]  =", arr[1:8:3])     # 20,50,80


arr[0]  = 10
arr[-1] = 90
arr[-3] = 70

arr[2:6]    = [30 40 50 60]
arr[:4]     = [10 20 30 40]
arr[5:]     = [60 70 80 90]
arr[::2]    = [10 30 50 70 90]
arr[::-1]   = [90 80 70 60 50 40 30 20 10]
arr[1:8:3]  = [20 50 80]


---
## 7️⃣ Indexing و Slicing (2D و D3) 🗂️

### القاعدة: `arr[row, col]` أو `arr[row][col]`


In [25]:
import numpy as np

matrix = np.array([[1,  2,  3,  4],
                   [5,  6,  7,  8],
                   [9, 10, 11, 12]])
print("Matrix:")
print(matrix)
print(f"Shape: {matrix.shape}")  # (3, 4)


Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Shape: (3, 4)


In [26]:
# Indexing في 2D
print("matrix[0, 0] =", matrix[0, 0])    # 1  — صف 0، عمود 0
print("matrix[1, 2] =", matrix[1, 2])    # 7  — صف 1، عمود 2
print("matrix[-1,-1]=", matrix[-1,-1])   # 12 — آخر عنصر

# Slicing في 2D
print("\nالصف الأول:    ", matrix[0])         # [1,2,3,4]
print("العمود الأول:   ", matrix[:, 0])       # [1,5,9]
print("أول صفين:      \n", matrix[:2])        # صفوف 0,1
print("أول صفين، أول 3 أعمدة:\n", matrix[:2, :3])


matrix[0, 0] = 1
matrix[1, 2] = 7
matrix[-1,-1]= 12

الصف الأول:     [1 2 3 4]
العمود الأول:    [1 5 9]
أول صفين:      
 [[1 2 3 4]
 [5 6 7 8]]
أول صفين، أول 3 أعمدة:
 [[1 2 3]
 [5 6 7]]


In [150]:
# Indexing في 3D
import numpy as np

tensor = np.arange(24).reshape(2, 3, 4)
print("Tensor (2, 3, 4):")
print(tensor)
print(f"\ntensor[0] =\n{tensor[0]}")        # أول matrix
print(f"\ntensor[1,2,3] = {tensor[1,2,3]}")  # آخر عنصر = 23
print(f"\ntensor[:, 0, :] =\n{tensor[:, 0, :]}")  # أول صف من كل matrix


Tensor (2, 3, 4):
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]

tensor[0] =
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

tensor[1,2,3] = 23

tensor[:, 0, :] =
[[ 0  1  2  3]
 [12 13 14 15]]


---
## 8️⃣ Fancy Indexing 🎩

> الوصول لعناصر بـ Array من indices — مش بـ slice.


In [29]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50, 60, 70, 80])

# Fancy Indexing — قائمة indices
print("arr[[0,2,5]]  =", arr[[0, 2, 5]])    # 10, 30, 60
print("arr[[1,1,3]]  =", arr[[1, 1, 3]])    # تكرار مسموح

# في 2D
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
rows = np.array([0, 1, 2])
cols = np.array([0, 1, 2])
print("\nDiagonal via fancy indexing:", matrix[rows, cols])  # 1,5,9

# اختيار صفوف معينة
print("\nالصفوف 0 و 2:\n", matrix[[0, 2]])


arr[[0,2,5]]  = [10 30 60]
arr[[1,1,3]]  = [20 20 40]

Diagonal via fancy indexing: [1 5 9]

الصفوف 0 و 2:
 [[1 2 3]
 [7 8 9]]


---
## 9️⃣ Boolean Indexing (Boolean Masking) 🎭

> **الأهم للـ ML** — الفلترة بالشروط.


In [31]:
import numpy as np

scores = np.array([45, 82, 91, 67, 55, 88, 73, 95, 61, 79])

# Boolean Mask
mask = scores > 75
print("Mask:", mask)
print("درجات أعلى من 75:", scores[mask])

# مباشرةً
print("درجات بين 60 و 80:", scores[(scores >= 60) & (scores <= 80)])
print("درجات < 60 أو > 90:", scores[(scores < 60) | (scores > 90)])


Mask: [False  True  True False False  True False  True False  True]
درجات أعلى من 75: [82 91 88 95 79]
درجات بين 60 و 80: [67 73 61 79]
درجات < 60 أو > 90: [45 91 55 95]


In [32]:
import numpy as np

data = np.array([1, -2, 3, -4, 5, -6, 7, -8])

# استبدال القيم السالبة بصفر
data_clean = data.copy()
data_clean[data_clean < 0] = 0
print("قبل:", data)
print("بعد:", data_clean)

# np.where — if/else للـ Arrays
result = np.where(data > 0, data, 0)   # لو موجب احتفظ بيه، لو سالب حوّله 0
print("np.where:", result)


قبل: [ 1 -2  3 -4  5 -6  7 -8]
بعد: [1 0 3 0 5 0 7 0]
np.where: [1 0 3 0 5 0 7 0]


---
## 🔟 تعديل الشكل (Reshaping) 🔄

> **مهم جداً في ML** — تغيير shape بدون تغيير البيانات.


In [34]:
import numpy as np

arr = np.arange(12)
print("Original:", arr, "| shape:", arr.shape)

# reshape
m_3x4 = arr.reshape(3, 4)
print("\nreshape(3,4):\n", m_3x4)

m_4x3 = arr.reshape(4, 3)
print("\nreshape(4,3):\n", m_4x3)

# -1 = اتحسب أوتوماتيك
m_2x6 = arr.reshape(2, -1)   # 2 صفوف، الأعمدة تتحسب
print("\nreshape(2,-1):\n", m_2x6)

m_col = arr.reshape(-1, 1)   # عمود واحد
print("\nreshape(-1,1) (column vector):\n", m_col)


Original: [ 0  1  2  3  4  5  6  7  8  9 10 11] | shape: (12,)

reshape(3,4):
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

reshape(4,3):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

reshape(2,-1):
 [[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]

reshape(-1,1) (column vector):
 [[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]]


In [35]:
import numpy as np

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

# flatten — إرجاع 1D Array (copy)
flat = matrix.flatten()
print("flatten():", flat)

# ravel — إرجاع 1D Array (view لو ممكن — أسرع)
rav = matrix.ravel()
print("ravel():", rav)

# transpose — قلب الصفوف والأعمدة
print("\nOriginal (3x3):\n", matrix)
print("\nTranspose (.T):\n", matrix.T)

# reshape مهم في الـ ML
X = np.random.randn(100, 28, 28)  # 100 صورة 28x28
X_flat = X.reshape(100, -1)       # flatten كل صورة لـ 784
print(f"\nصور: {X.shape} → flatten: {X_flat.shape}")


flatten(): [1 2 3 4 5 6 7 8 9]
ravel(): [1 2 3 4 5 6 7 8 9]

Original (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Transpose (.T):
 [[1 4 7]
 [2 5 8]
 [3 6 9]]

صور: (100, 28, 28) → flatten: (100, 784)


---
## 1️⃣1️⃣ العمليات الحسابية الأساسية ➕➖✖️➗

> **Vectorized Operations** — بتشتغل على كل عنصر بدون loop.


In [37]:
import numpy as np

a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])

print("a + b  =", a + b)
print("a - b  =", a - b)
print("a * b  =", a * b)
print("a / b  =", a / b)
print("a ** 2 =", a ** 2)   # تربيع
print("a % 3  =", a % 3)    # باقي القسمة
print("b // 3 =", b // 3)   # قسمة صحيحة


a + b  = [11 22 33 44 55]
a - b  = [ -9 -18 -27 -36 -45]
a * b  = [ 10  40  90 160 250]
a / b  = [0.1 0.1 0.1 0.1 0.1]
a ** 2 = [ 1  4  9 16 25]
a % 3  = [1 2 0 1 2]
b // 3 = [ 3  6 10 13 16]


In [38]:
import numpy as np

# العمليات مع Scalar (Broadcasting أبسط صورة)
arr = np.array([1, 2, 3, 4, 5])
print("arr + 10  =", arr + 10)
print("arr * 3   =", arr * 3)
print("arr / 2   =", arr / 2)
print("arr ** 2  =", arr ** 2)

# مقارنات — بترجع Boolean Array
print("\narr > 3 =", arr > 3)
print("arr == 3 =", arr == 3)


arr + 10  = [11 12 13 14 15]
arr * 3   = [ 3  6  9 12 15]
arr / 2   = [0.5 1.  1.5 2.  2.5]
arr ** 2  = [ 1  4  9 16 25]

arr > 3 = [False False False  True  True]
arr == 3 = [False False  True False False]


In [39]:
import numpy as np

# ضرب المصفوفات — element-wise vs dot product
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])

print("A * B (element-wise):\n", A * B)
print("\nA @ B (matrix multiplication):\n", A @ B)
print("\nnp.dot(A, B):\n", np.dot(A, B))


A * B (element-wise):
 [[ 5 12]
 [21 32]]

A @ B (matrix multiplication):
 [[19 22]
 [43 50]]

np.dot(A, B):
 [[19 22]
 [43 50]]


In [ ]:
[ [1*5 + 2*7, 1*6 + 2*8],
  [3*5 + 4*7, 3*6 + 4*8] ]
= [[19, 22],
   [43, 50]]

---
## 1️⃣2️⃣ Universal Functions (ufuncs) 🧮

> دوال رياضية vectorized — بتشتغل على كل عنصر مرة واحدة.


In [41]:
import numpy as np

arr = np.array([1, 4, 9, 16, 25, 36])

# الدوال الأساسية
print("sqrt:", np.sqrt(arr))
print("square:", np.square(arr))
print("abs:", np.abs(np.array([-1, -2, 3, -4])))
print("log:", np.log(arr))          # log طبيعي
print("log2:", np.log2(arr))
print("log10:", np.log10(arr))
print("exp:", np.exp(np.array([0, 1, 2])))  # e^x


sqrt: [1. 2. 3. 4. 5. 6.]
square: [   1   16   81  256  625 1296]
abs: [1 2 3 4]
log: [0.         1.38629436 2.19722458 2.77258872 3.21887582 3.58351894]
log2: [0.         2.         3.169925   4.         4.64385619 5.169925  ]
log10: [0.         0.60205999 0.95424251 1.20411998 1.39794001 1.5563025 ]
exp: [1.         2.71828183 7.3890561 ]


| الدالة        | معنى                    | مثال                        |
| ------------- | ----------------------- | --------------------------- |
| `np.sqrt()`   | الجذر التربيعي لكل عنصر | sqrt([1,4,9]) → [1,2,3]     |
| `np.square()` | تربيع كل عنصر           | square([1,2]) → [1,4]       |
| `np.abs()`    | القيمة المطلقة          | abs([-1,-2]) → [1,2]        |
| `np.log()`    | اللوغاريتم الطبيعي (ln) | log([1, e]) → [0,1]         |
| `np.log2()`   | لوغاريتم أساسه 2        | log2([1,2,4]) → [0,1,2]     |
| `np.log10()`  | لوغاريتم أساسه 10       | log10([1,10,100]) → [0,1,2] |
| `np.exp()`    | الأس (e^x)              | exp([0,1]) → [1,2.718]      |


In [42]:
import numpy as np

# الدوال المثلثية
angles = np.linspace(0, np.pi, 5)
print("angles (rad):", angles.round(3))
print("sin:", np.sin(angles).round(3))
print("cos:", np.cos(angles).round(3))

# الدوال الإحصائية
arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3])
print("\nceil:", np.ceil(np.array([1.2, 2.7, 3.1])))
print("floor:", np.floor(np.array([1.9, 2.7, 3.9])))
print("round:", np.round(np.array([1.4567, 2.678, 3.333]), 2))

# clip — تحديد نطاق
print("\nclip(2,7):", np.clip(arr, 2, 7))  # أقل من 2 → 2، أكتر من 7 → 7


angles (rad): [0.    0.785 1.571 2.356 3.142]
sin: [0.    0.707 1.    0.707 0.   ]
cos: [ 1.     0.707  0.    -0.707 -1.   ]

ceil: [2. 3. 4.]
floor: [1. 2. 3.]
round: [1.46 2.68 3.33]

clip(2,7): [3 2 4 2 5 7 2 6 5 3]


| الدالة     | وظيفتها                     |
| ---------- | --------------------------- |
| `sin, cos` | تحويل الزوايا لقيم (-1 → 1) |
| `ceil`     | تقريب لأعلى                 |
| `floor`    | تقريب لأسفل                 |
| `round`    | تقريب لعدد خانات            |
| `clip`     | تحديد نطاق القيم            |


---
## 1️⃣3️⃣ Aggregation Functions 📊

> دوال التلخيص والإحصاء — بتشتغل على الـ Array كلها أو على axis معين.


In [44]:
import numpy as np

arr = np.array([3, 1, 4, 1, 5, 9, 2, 6, 5, 3])

print(f"sum    = {np.sum(arr)}")
print(f"mean   = {np.mean(arr)}")
print(f"median = {np.median(arr)}")
print(f"std    = {np.std(arr):.3f}")      # انحراف معياري
print(f"var    = {np.var(arr):.3f}")      # تباين
print(f"min    = {np.min(arr)}")
print(f"max    = {np.max(arr)}")
print(f"argmin = {np.argmin(arr)}")       # index أصغر قيمة
print(f"argmax = {np.argmax(arr)}")       # index أكبر قيمة
print(f"cumsum = {np.cumsum(arr)}")       # مجموع تراكمي
print(f"cumprod= {np.cumprod(np.array([1,2,3,4,5]))}")  # ضرب تراكمي


sum    = 39
mean   = 3.9
median = 3.5
std    = 2.343
var    = 5.490
min    = 1
max    = 9
argmin = 1
argmax = 5
cumsum = [ 3  4  8  9 14 23 25 31 36 39]
cumprod= [  1   2   6  24 120]


In [45]:
import numpy as np

# axis في 2D — مهم جداً
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Matrix:")
print(matrix)

print("\nsum (كل العناصر):", np.sum(matrix))
print("sum axis=0 (عمودي ↓):", np.sum(matrix, axis=0))   # مجموع كل عمود
print("sum axis=1 (أفقي →):", np.sum(matrix, axis=1))    # مجموع كل صف
print("mean axis=0:", np.mean(matrix, axis=0))
print("max axis=1:", np.max(matrix, axis=1))


Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

sum (كل العناصر): 45
sum axis=0 (عمودي ↓): [12 15 18]
sum axis=1 (أفقي →): [ 6 15 24]
mean axis=0: [4. 5. 6.]
max axis=1: [3 6 9]


In [46]:
import numpy as np

# Percentiles
data = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
print("25th percentile:", np.percentile(data, 25))
print("50th percentile:", np.percentile(data, 50))   # = median
print("75th percentile:", np.percentile(data, 75))
print("IQR:", np.percentile(data, 75) - np.percentile(data, 25))

# الـ Quantile بديل للـ percentile
print("\n0.25 quantile:", np.quantile(data, 0.25))


25th percentile: 32.5
50th percentile: 55.0
75th percentile: 77.5
IQR: 45.0

0.25 quantile: 32.5


---
## 1️⃣4️⃣ Broadcasting 📡

> أحد أقوى ميزات NumPy — العمليات بين Arrays مختلفة الشكل.

### القواعد:
1. لو الـ ndim مختلف → الأصغر بيتوسع من الشمال
2. الـ dimensions بتتطابق لو قيمتها متساوية أو واحدة منهم 1
3. الـ dimension اللي قيمتها 1 بتتمدد لتطابق التانية


In [48]:
import numpy as np

# Broadcasting بسيط: Scalar + Array
arr = np.array([1, 2, 3, 4, 5])
print("arr + 10:", arr + 10)   # 10 بتتطبق على كل عنصر

# 1D + 1D (نفس الحجم)
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])
print("a + b:", a + b)


arr + 10: [11 12 13 14 15]
a + b: [11 22 33]


In [49]:
import numpy as np

# Broadcasting في 2D
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
row = np.array([10, 20, 30])   # shape (3,)

print("Matrix + row (يضيف row لكل صف):")
print(matrix + row)

col = np.array([[10],           # shape (3, 1)
                [20],
                [30]])
print("\nMatrix + col (يضيف col لكل عمود):")
print(matrix + col)


Matrix + row (يضيف row لكل صف):
[[11 22 33]
 [14 25 36]
 [17 28 39]]

Matrix + col (يضيف col لكل عمود):
[[11 12 13]
 [24 25 26]
 [37 38 39]]


In [50]:
import numpy as np

# مثال عملي في ML: Normalization
data = np.array([[1.0, 200.0, 0.5],
                 [2.0, 150.0, 0.8],
                 [3.0, 300.0, 0.3]])

mean = data.mean(axis=0)   # mean لكل feature
std  = data.std(axis=0)    # std لكل feature

# Z-score normalization — Broadcasting يخلي الحساب سهل
data_norm = (data - mean) / std

print("mean:", mean)
print("std: ", std)
print("\nNormalized data:")
print(data_norm.round(3))
print("\nمتوسط بعد النورمالايزيشن:", data_norm.mean(axis=0).round(10))


mean: [  2.         216.66666667   0.53333333]
std:  [ 0.81649658 62.36095645  0.20548047]

Normalized data:
[[-1.225 -0.267 -0.162]
 [ 0.    -1.069  1.298]
 [ 1.225  1.336 -1.136]]

متوسط بعد النورمالايزيشن: [0. 0. 0.]


✅ الطبيعي بعد normalization:

المتوسط ≈ 0

أغلب القيم بين -3 و +3

❌ لو شوفت كده يبقى في مشكلة:

قيم زي 5 أو -6 → Outlier 🚨

Feature كله أصفار → ملوش لازمة ❌

المتوسط مش 0 → الحساب غلط ❌

✔️ في Z-score:

mean ≈ 0

std ≈ 1

---
## 1️⃣5️⃣ Linear Algebra 🔢

> **قلب الـ ML** — كل الـ models بتستخدم Linear Algebra.


In [52]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

# ضرب المصفوفات
print("A @ B:")
print(A @ B)

# Transpose
print("\nA.T:")
print(A.T)

# Determinant
print("\ndet(A):", np.linalg.det(A))

# Inverse
print("\ninv(A):")
print(np.linalg.inv(A).round(3))

# Verification: A × inv(A) = I
print("\nA @ inv(A) = I?")
print((A @ np.linalg.inv(A)).round(10))


A @ B:
[[19 22]
 [43 50]]

A.T:
[[1 3]
 [2 4]]

det(A): -2.0000000000000004

inv(A):
[[-2.   1. ]
 [ 1.5 -0.5]]

A @ inv(A) = I?
[[1. 0.]
 [0. 1.]]


In [53]:
import numpy as np

# Eigenvalues و Eigenvectors
A = np.array([[4, 1],
              [2, 3]])

eigenvalues, eigenvectors = np.linalg.eig(A)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

# Norm
v = np.array([3, 4])
print("\nL2 Norm:", np.linalg.norm(v))    # = 5
print("L1 Norm:", np.linalg.norm(v, ord=1)) # = 7

# Solve: Ax = b
A = np.array([[2, 1], [1, 3]])
b = np.array([8, 13])
x = np.linalg.solve(A, b)
print("\nحل المعادلة Ax=b:", x)
print("التحقق:", A @ x)


Eigenvalues: [5. 2.]
Eigenvectors:
 [[ 0.70710678 -0.4472136 ]
 [ 0.70710678  0.89442719]]

L2 Norm: 5.0
L1 Norm: 7.0

حل المعادلة Ax=b: [2.2 3.6]
التحقق: [ 8. 13.]


---
## 1️⃣6️⃣ Random Module 🎲

> **مهم جداً في ML** — تهيئة الـ weights، تقسيم البيانات، simulation.


In [55]:
import numpy as np

# seed — لضمان التكرارية (reproducibility)
np.random.seed(42)

# rand — uniform [0, 1)
print("rand(5):", np.random.rand(5))
print("rand(2,3):\n", np.random.rand(2, 3))

# randn — Standard Normal (mean=0, std=1)
print("\nrandn(5):", np.random.randn(5))

# randint — أعداد صحيحة عشوائية
print("\nrandint(0, 10, size=8):", np.random.randint(0, 10, size=8))


rand(5): [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
rand(2,3):
 [[0.15599452 0.05808361 0.86617615]
 [0.60111501 0.70807258 0.02058449]]

randn(5): [-0.58087813 -0.52516981 -0.57138017 -0.92408284 -2.61254901]

randint(0, 10, size=8): [0 9 2 6 3 8 2 4]


In [56]:
import numpy as np
np.random.seed(0)

# normal — normal distribution بـ mean و std محددين
samples = np.random.normal(loc=170, scale=10, size=1000)  # أطوال البشر
print(f"Normal distribution: mean={samples.mean():.1f}, std={samples.std():.1f}")

# uniform — توزيع منتظم
u = np.random.uniform(low=0, high=100, size=5)
print("uniform:", u.round(2))

# choice — اختيار عشوائي
arr = np.array([10, 20, 30, 40, 50])
print("choice(3):", np.random.choice(arr, 3))
print("choice(3, replace=False):", np.random.choice(arr, 3, replace=False))  # بدون تكرار


Normal distribution: mean=169.5, std=9.9
uniform: [82.19 70.05 88.31 96.66 77.47]
choice(3): [50 20 40]
choice(3, replace=False): [30 10 20]


In [57]:
import numpy as np
np.random.seed(1)

# shuffle — خلط
arr = np.arange(10)
np.random.shuffle(arr)
print("shuffle:", arr)

# permutation — نفس shuffle لكن بيرجع نسخة جديدة
arr2 = np.arange(10)
print("permutation:", np.random.permutation(arr2))
print("arr2 لم يتغير:", arr2)

# مثال ML: تقسيم train/test
data = np.arange(100)
indices = np.random.permutation(100)
train_idx = indices[:80]
test_idx  = indices[80:]
print(f"\nTrain: {len(train_idx)} samples | Test: {len(test_idx)} samples")


shuffle: [2 9 6 4 0 3 1 7 8 5]
permutation: [9 5 3 0 8 4 2 1 6 7]
arr2 لم يتغير: [0 1 2 3 4 5 6 7 8 9]

Train: 80 samples | Test: 20 samples


---
## 1️⃣7️⃣ Sorting و Searching 🔍


In [59]:
import numpy as np

arr = np.array([64, 25, 12, 43, 8, 91, 37])

# sort — ترتيب تصاعدي (copy)
print("sorted:", np.sort(arr))
print("original:", arr)   # لم يتغير

# sort inplace
arr_copy = arr.copy()
arr_copy.sort()
print("inplace sort:", arr_copy)

# argsort — بيرجع الـ indices بترتيب الـ sort
print("\nargsort:", np.argsort(arr))
print("arr[argsort]:", arr[np.argsort(arr)])   # نفس np.sort


sorted: [ 8 12 25 37 43 64 91]
original: [64 25 12 43  8 91 37]
inplace sort: [ 8 12 25 37 43 64 91]

argsort: [4 2 1 6 3 0 5]
arr[argsort]: [ 8 12 25 37 43 64 91]


In [60]:
import numpy as np

arr = np.array([64, 25, 12, 43, 8, 91, 37])

# أكبر K قيم
k = 3
top_k_idx = np.argsort(arr)[-k:][::-1]
print(f"أكبر {k} قيم:", arr[top_k_idx])

# where — البحث عن indices بشرط
print("\nindices حيث arr > 40:", np.where(arr > 40))
print("قيم arr > 40:", arr[np.where(arr > 40)])

# searchsorted — البحث في Array مرتبة
sorted_arr = np.sort(arr)
print("\nSorted:", sorted_arr)
print("مكان إدراج 50:", np.searchsorted(sorted_arr, 50))


أكبر 3 قيم: [91 64 43]

indices حيث arr > 40: (array([0, 3, 5], dtype=int64),)
قيم arr > 40: [64 43 91]

Sorted: [ 8 12 25 37 43 64 91]
مكان إدراج 50: 5


---
## 1️⃣8️⃣ دمج وتقسيم Arrays 🔗


In [62]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

# concatenate — دمج على axis
print("concatenate 1D:", np.concatenate([a, b, c]))

# 2D
A = np.array([[1,2],[3,4]])
B = np.array([[5,6],[7,8]])
print("\nconcatenate axis=0 (عمودي):")
print(np.concatenate([A, B], axis=0))
print("\nconcatenate axis=1 (أفقي):")
print(np.concatenate([A, B], axis=1))


concatenate 1D: [1 2 3 4 5 6 7 8 9]

concatenate axis=0 (عمودي):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

concatenate axis=1 (أفقي):
[[1 2 5 6]
 [3 4 7 8]]


In [63]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# vstack — تكديس عمودي
print("vstack:")
print(np.vstack([a, b]))

# hstack — تكديس أفقي
print("\nhstack:")
print(np.hstack([a, b]))

# stack — بُعد جديد
print("\nstack axis=0:")
print(np.stack([a, b], axis=0))  # shape (2,3)
print("\nstack axis=1:")
print(np.stack([a, b], axis=1))  # shape (3,2)


vstack:
[[1 2 3]
 [4 5 6]]

hstack:
[1 2 3 4 5 6]

stack axis=0:
[[1 2 3]
 [4 5 6]]

stack axis=1:
[[1 4]
 [2 5]
 [3 6]]


In [64]:
import numpy as np

# split — تقسيم
arr = np.arange(12)
print("Original:", arr)
print("split إلى 3:", np.split(arr, 3))
print("split في [4,8]:", np.split(arr, [4, 8]))

# vsplit و hsplit
matrix = np.arange(16).reshape(4, 4)
print("\nMatrix:")
print(matrix)
top, bottom = np.vsplit(matrix, 2)
print("vsplit top:")
print(top)
left, right = np.hsplit(matrix, 2)
print("hsplit left:")
print(left)


Original: [ 0  1  2  3  4  5  6  7  8  9 10 11]
split إلى 3: [array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]
split في [4,8]: [array([0, 1, 2, 3]), array([4, 5, 6, 7]), array([ 8,  9, 10, 11])]

Matrix:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
vsplit top:
[[0 1 2 3]
 [4 5 6 7]]
hsplit left:
[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]


---
## 1️⃣9️⃣ التعامل مع القيم المفقودة (NaN) 🕳️

> **NaN = Not a Number** — يظهر في القسمة على صفر، sqrt سالب، وبيانات ناقصة.


In [66]:
import numpy as np

arr = np.array([1.0, 2.0, np.nan, 4.0, np.nan, 6.0])
print("Array:", arr)

# اكتشاف NaN
print("isnan:", np.isnan(arr))
print("عدد NaN:", np.isnan(arr).sum())
print("هل في NaN؟", np.any(np.isnan(arr)))


Array: [ 1.  2. nan  4. nan  6.]
isnan: [False False  True False  True False]
عدد NaN: 2
هل في NaN؟ True


In [67]:
import numpy as np

arr = np.array([1.0, 2.0, np.nan, 4.0, np.nan, 6.0])

# nan-safe functions — تتجاهل NaN
print("sum (عادي):", np.sum(arr))        # nan!
print("nansum:", np.nansum(arr))         # 13.0

print("mean (عادي):", np.mean(arr))      # nan!
print("nanmean:", np.nanmean(arr))       # 3.25

print("nanstd:", np.nanstd(arr))
print("nanmin:", np.nanmin(arr))
print("nanmax:", np.nanmax(arr))

# استبدال NaN
arr_filled = np.where(np.isnan(arr), np.nanmean(arr), arr)
print("\nبعد استبدال NaN بالمتوسط:", arr_filled)


sum (عادي): nan
nansum: 13.0
mean (عادي): nan
nanmean: 3.25
nanstd: 1.920286436967152
nanmin: 1.0
nanmax: 6.0

بعد استبدال NaN بالمتوسط: [1.   2.   3.25 4.   3.25 6.  ]


In [68]:
import numpy as np

# inf و -inf
print("1/0 =", np.float64(1) / np.float64(0))   # inf
print("log(0) =", np.log(0))                      # -inf
print("0/0 =", np.float64(0) / np.float64(0))    # nan

arr = np.array([1.0, np.inf, 3.0, -np.inf, np.nan])
print("\nisinf:", np.isinf(arr))
print("isfinite:", np.isfinite(arr))
print("isnan:", np.isnan(arr))


1/0 = inf
log(0) = -inf
0/0 = nan

isinf: [False  True False  True False]
isfinite: [ True False  True False False]
isnan: [False False False False  True]


C:\Users\FreeComp\AppData\Local\Temp\ipykernel_18516\3649734345.py:4: RuntimeWarning: divide by zero encountered in scalar divide
  print("1/0 =", np.float64(1) / np.float64(0))   # inf
C:\Users\FreeComp\AppData\Local\Temp\ipykernel_18516\3649734345.py:5: RuntimeWarning: divide by zero encountered in log
  print("log(0) =", np.log(0))                      # -inf
C:\Users\FreeComp\AppData\Local\Temp\ipykernel_18516\3649734345.py:6: RuntimeWarning: invalid value encountered in scalar divide
  print("0/0 =", np.float64(0) / np.float64(0))    # nan


---
## 2️⃣0️⃣ Array Copy vs View ⚠️

> **أهم concept يفهمه الطالب عشان يتجنب bugs صعبة!**


In [70]:
import numpy as np

# VIEW — نفس البيانات في الذاكرة
original = np.array([1, 2, 3, 4, 5])
view = original[1:4]       # slicing = view
print("original:", original)
print("view:", view)

view[0] = 999              # تعديل الـ view
print("\nبعد تعديل view[0] = 999:")
print("original:", original)   # ⚠️ اتغير هو كمان!
print("view:", view)


original: [1 2 3 4 5]
view: [2 3 4]

بعد تعديل view[0] = 999:
original: [  1 999   3   4   5]
view: [999   3   4]


In [71]:
import numpy as np

# COPY — نسخة مستقلة
original = np.array([1, 2, 3, 4, 5])
copy = original[1:4].copy()   # .copy() = نسخة حقيقية
copy[0] = 999

print("original:", original)  # ✅ لم يتغير
print("copy:", copy)

# كيف تعرف لو view أو copy؟
view = original[1:4]
print("\nview.base is original:", view.base is original)  # True = view
copy = original[1:4].copy()
print("copy.base is None:", copy.base is None)             # True = copy


original: [1 2 3 4 5]
copy: [999   3   4]

view.base is original: True
copy.base is None: True


### 📌 متى يكون View ومتى يكون Copy؟

| العملية | النتيجة | الملاحظة |
|---------|---------|---------|
| `arr[1:4]` | View | Slicing = view |
| `arr[[0,2,4]]` | Copy | Fancy Indexing = copy |
| `arr[arr > 0]` | Copy | Boolean Indexing = copy |
| `arr.reshape(...)` | View (غالباً) | لو الذاكرة contiguous |
| `arr.flatten()` | Copy | دايماً copy |
| `arr.ravel()` | View (لو ممكن) | أسرع من flatten |
| `arr.copy()` | Copy | صريح |

> 🔑 **القاعدة:** لو مش متأكد، اعمل `.copy()` — هتوفر عليك debug ساعات.


---
## 2️⃣1️⃣ Vectorization بدل Loops ⚡

> **أهم درس في NumPy للـ ML** — الـ loops في Python بطيئة جداً.


In [74]:
import numpy as np
import time

n = 1_000_000

# ── طريقة 1: Python loop ──
a = list(range(n))
t0 = time.time()
result = [x**2 + 2*x + 1 for x in a]
t_loop = time.time() - t0

# ── طريقة 2: NumPy Vectorized ──
arr = np.arange(n, dtype=np.float64)
t0 = time.time()
result = arr**2 + 2*arr + 1
t_vec = time.time() - t0

print(f"Python Loop:    {t_loop*1000:.1f} ms")
print(f"NumPy Vectors:  {t_vec*1000:.1f} ms")
print(f"تسريع: {t_loop/t_vec:.0f}x")


Python Loop:    537.4 ms
NumPy Vectors:  53.6 ms
تسريع: 10x


In [75]:
import numpy as np

# مثال: حساب Euclidean Distance
# بدون Vectorization
def euclidean_loop(a, b):
    total = 0
    for x, y in zip(a, b):
        total += (x - y) ** 2
    return total ** 0.5

# مع Vectorization
def euclidean_vectorized(a, b):
    return np.sqrt(np.sum((a - b) ** 2))

a = np.random.randn(1000)
b = np.random.randn(1000)

import time
t0 = time.time()
for _ in range(1000): euclidean_loop(a, b)
t_loop = time.time() - t0

t0 = time.time()
for _ in range(1000): euclidean_vectorized(a, b)
t_vec = time.time() - t0

print(f"Loop:       {t_loop*1000:.1f} ms")
print(f"Vectorized: {t_vec*1000:.1f} ms")
print(f"تسريع: {t_loop/t_vec:.0f}x")


Loop:       1422.1 ms
Vectorized: 42.4 ms
تسريع: 34x


In [76]:
import numpy as np

# مثال ML: حساب predictions
# y = Wx + b   ← نموذج Linear

W = np.random.randn(5, 3)   # weights (5 neurons, 3 inputs)
b = np.random.randn(5)       # biases
X = np.random.randn(100, 3)  # 100 samples, 3 features

# Forward pass — vectorized
# (100,3) @ (3,5) + (5,) = (100,5)
output = X @ W.T + b
print(f"Input shape:  {X.shape}")
print(f"Output shape: {output.shape}")
print("نتيجة Forward Pass (أول 3 samples):")
print(output[:3].round(3))


Input shape:  (100, 3)
Output shape: (100, 5)
نتيجة Forward Pass (أول 3 samples):
[[-0.704  1.709  1.091 -5.736  8.163]
 [-0.127 -0.859 -0.333 -0.415 -2.226]
 [-0.362 -1.591 -0.92   0.3   -3.146]]


---
## 2️⃣2️⃣ NumPy و Pandas 🤝

> فهم العلاقة بينهم بيخلي الطالب يفهم إيه اللي بيحصل جوا Pandas.


In [78]:
import numpy as np
import pandas as pd

# DataFrame مبنية فوق NumPy Arrays
df = pd.DataFrame({'A': [1,2,3,4,5], 'B': [10,20,30,40,50]})

# استخراج الـ NumPy array من DataFrame
arr = df.values               # أو df.to_numpy()
print("df.values:", arr)
print("type:", type(arr))
print("dtype:", arr.dtype)


df.values: [[ 1 10]
 [ 2 20]
 [ 3 30]
 [ 4 40]
 [ 5 50]]
type: <class 'numpy.ndarray'>
dtype: int64


In [79]:
import numpy as np
import pandas as pd

# من NumPy إلى Pandas وبالعكس
np_arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

# np → DataFrame
df = pd.DataFrame(np_arr, columns=['X','Y','Z'])
print("DataFrame من NumPy:")
print(df)

# DataFrame → np
back_to_np = df.values
print("\nرجع لـ NumPy:", back_to_np)


DataFrame من NumPy:
   X  Y  Z
0  1  2  3
1  4  5  6
2  7  8  9

رجع لـ NumPy: [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [80]:
import numpy as np
import pandas as pd

# np.nan في Pandas
arr = np.array([1.0, np.nan, 3.0, np.nan, 5.0])
s = pd.Series(arr)
print("Series مع NaN:")
print(s)
print("\nisnull:", s.isnull().values)
print("fillna(0):", s.fillna(0).values)

# لما Pandas بتعمل groupby/mean — جوّاها بتستخدم NumPy


Series مع NaN:
0    1.0
1    NaN
2    3.0
3    NaN
4    5.0
dtype: float64

isnull: [False  True False  True False]
fillna(0): [1. 0. 3. 0. 5.]


---
## 2️⃣3️⃣ مشروع تطبيقي متكامل 🚀

### 📋 تحليل إحصائي كامل لدرجات طلاب + محاكاة نموذج ML بسيط


In [82]:
import numpy as np
np.random.seed(42)

# ── الجزء 1: تحليل درجات الطلاب ──
print("=" * 50)
print("PART 1: تحليل درجات الطلاب")
print("=" * 50)

n_students = 200
scores = np.random.normal(loc=72, scale=15, size=n_students)
scores = np.clip(scores, 0, 100).round(1)

# إحصاءات
print(f"عدد الطلاب: {n_students}")
print(f"المتوسط:    {scores.mean():.2f}")
print(f"الوسيط:     {np.median(scores):.2f}")
print(f"الانحراف:   {scores.std():.2f}")
print(f"الأدنى:     {scores.min():.1f}")
print(f"الأعلى:     {scores.max():.1f}")
print(f"IQR:        {(np.percentile(scores,75) - np.percentile(scores,25)):.2f}")


PART 1: تحليل درجات الطلاب
عدد الطلاب: 200
المتوسط:    71.25
الوسيط:     71.95
الانحراف:   13.60
الأدنى:     32.7
الأعلى:     100.0
IQR:        18.10


In [83]:
import numpy as np
np.random.seed(42)

scores = np.clip(np.random.normal(72, 15, 200), 0, 100).round(1)

# ── تصنيف الدرجات ──
grades = np.where(scores >= 90, 'A',
         np.where(scores >= 80, 'B',
         np.where(scores >= 70, 'C',
         np.where(scores >= 60, 'D', 'F'))))

unique, counts = np.unique(grades, return_counts=True)
print("توزيع الدرجات:")
for g, c in sorted(zip(unique, counts)):
    pct = c/len(grades)*100
    bar = '█' * int(pct/2)
    print(f"  {g}: {c:3d} طالب ({pct:.1f}%)  {bar}")

# نسبة النجاح
pass_rate = (scores >= 60).mean() * 100
print(f"\nنسبة النجاح: {pass_rate:.1f}%")


توزيع الدرجات:
  A:  18 طالب (9.0%)  ████
  B:  30 طالب (15.0%)  ███████
  C:  61 طالب (30.5%)  ███████████████
  D:  46 طالب (23.0%)  ███████████
  F:  45 طالب (22.5%)  ███████████

نسبة النجاح: 77.5%


In [84]:
import numpy as np
np.random.seed(42)

# ── الجزء 2: محاكاة Linear Regression ──
print("=" * 50)
print("PART 2: Linear Regression من الصفر")
print("=" * 50)

# بيانات: y = 2x + 5 + noise
X = np.linspace(0, 10, 100)
y = 2 * X + 5 + np.random.randn(100) * 2

# Normal Equation: w = (X^T X)^-1 X^T y
X_mat = np.column_stack([np.ones(100), X])   # أضف bias column
w = np.linalg.solve(X_mat.T @ X_mat, X_mat.T @ y)

print(f"المعاملات الحقيقية: w0=5,   w1=2")
print(f"المعاملات المحسوبة: w0={w[0]:.4f}, w1={w[1]:.4f}")

# Predictions
y_pred = X_mat @ w

# Metrics
mse  = np.mean((y - y_pred) ** 2)
rmse = np.sqrt(mse)
mae  = np.mean(np.abs(y - y_pred))
ss_res = np.sum((y - y_pred)**2)
ss_tot = np.sum((y - y.mean())**2)
r2 = 1 - ss_res/ss_tot

print(f"\nMSE:  {mse:.4f}")
print(f"RMSE: {rmse:.4f}")
print(f"MAE:  {mae:.4f}")
print(f"R2:   {r2:.4f}")


PART 2: Linear Regression من الصفر
المعاملات الحقيقية: w0=5,   w1=2
المعاملات المحسوبة: w0=4.6544, w1=2.0276

MSE:  3.2596
RMSE: 1.8054
MAE:  1.4299
R2:   0.9147


In [85]:
import numpy as np
np.random.seed(0)

# ── الجزء 3: Neural Network Forward Pass ──
print("=" * 50)
print("PART 3: Neural Network Forward Pass")
print("=" * 50)

def relu(x):    return np.maximum(0, x)
def sigmoid(x): return 1 / (1 + np.exp(-x))
def softmax(x):
    e = np.exp(x - x.max(axis=1, keepdims=True))
    return e / e.sum(axis=1, keepdims=True)

# Architecture: 4 input → 8 hidden → 3 output
n_samples, n_input, n_hidden, n_output = 10, 4, 8, 3

X  = np.random.randn(n_samples, n_input)
W1 = np.random.randn(n_input, n_hidden) * 0.1
b1 = np.zeros(n_hidden)
W2 = np.random.randn(n_hidden, n_output) * 0.1
b2 = np.zeros(n_output)

# Forward
z1 = X  @ W1 + b1
a1 = relu(z1)
z2 = a1 @ W2 + b2
a2 = softmax(z2)

print(f"Input:       {X.shape}")
print(f"Hidden:      {a1.shape}  (after ReLU)")
print(f"Output:      {a2.shape}  (after Softmax)")
print(f"\nProbabilities (first 3 samples):")
print(a2[:3].round(3))
print(f"\nSum of probabilities: {a2.sum(axis=1)[:3]}")  # كل صف = 1


PART 3: Neural Network Forward Pass
Input:       (10, 4)
Hidden:      (10, 8)  (after ReLU)
Output:      (10, 3)  (after Softmax)

Probabilities (first 3 samples):
[[0.347 0.34  0.313]
 [0.342 0.338 0.319]
 [0.333 0.337 0.33 ]]

Sum of probabilities: [1. 1. 1.]


---
## 🎯 ملخص NumPy الكامل

```
📌 np.array()          → إنشاء Array
📌 shape, ndim, dtype  → معرفة خصائص الـ Array
📌 zeros, ones, arange, linspace, random → arrays جاهزة
📌 arr[i], arr[i:j]    → Indexing و Slicing
📌 arr[condition]      → Boolean Indexing ← مهم للـ ML
📌 reshape, flatten, T → تغيير الشكل
📌 +, -, *, /          → Vectorized operations
📌 np.sum, mean, std   → Aggregation مع axis
📌 Broadcasting        → عمليات على أشكال مختلفة
📌 np.linalg           → Linear Algebra ← قلب الـ ML
📌 np.random           → توليد بيانات عشوائية
📌 np.sort, argsort    → الترتيب
📌 np.nan, isnan       → التعامل مع القيم المفقودة
📌 .copy()             → تجنب تعديل الـ original
📌 Vectorization       → بدل Loops ← أسرع بـ 100x
```

### 🚀 الخطوات التالية:
1. **Pandas** — بتستخدم NumPy في الخلفية
2. **Matplotlib** — رسم البيانات
3. **Scikit-learn** — كل الـ input هو NumPy arrays
4. **Deep Learning** — PyTorch/TensorFlow بنفس مبادئ NumPy

---
> 💪 **NumPy = الأساس. بعد ما تفهمها كويس، كل المكتبات التانية هتبقى سهلة!**
